title : Amnesty 121
tagline: "Chaville, Velizy, Viroflay, Ville-D'Avray"

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/pdf"
  - scope:
      path: "assets/fonts"
